package com.dataprocess_server.dao;

import com.dataprocess_server.entity.DataInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DataInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovation..data_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovation..data_info
     *
     * @mbg.generated
     */
    int insert(DataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovation..data_info
     *
     * @mbg.generated
     */
    DataInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovation..data_info
     *
     * @mbg.generated
     */
    List<DataInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovation..data_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataInfo record);
}