package com.dataprocess_server.entity;

public class DataInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation..data_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation..data_info.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation..data_info.client_time
     *
     * @mbg.generated
     */
    private Long clientTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation..data_info.air_para
     *
     * @mbg.generated
     */
    private Integer airPara;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation..data_info.id
     *
     * @return the value of innovation..data_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation..data_info.id
     *
     * @param id the value for innovation..data_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation..data_info.client_id
     *
     * @return the value of innovation..data_info.client_id
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation..data_info.client_id
     *
     * @param clientId the value for innovation..data_info.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation..data_info.client_time
     *
     * @return the value of innovation..data_info.client_time
     *
     * @mbg.generated
     */
    public Long getClientTime() {
        return clientTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation..data_info.client_time
     *
     * @param clientTime the value for innovation..data_info.client_time
     *
     * @mbg.generated
     */
    public void setClientTime(Long clientTime) {
        this.clientTime = clientTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation..data_info.air_para
     *
     * @return the value of innovation..data_info.air_para
     *
     * @mbg.generated
     */
    public Integer getAirPara() {
        return airPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation..data_info.air_para
     *
     * @param airPara the value for innovation..data_info.air_para
     *
     * @mbg.generated
     */
    public void setAirPara(Integer airPara) {
        this.airPara = airPara;
    }
}